# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Potager.destroy_all
Vegetable.destroy_all
User.destroy_all

puts "creating users..."
toto = User.create!({
  email: 'toto@terra.fr',
  password: 'azerty',
 })

bob = User.create!({
  email: 'bob@terra.fr',
  password: 'azerty',
 })

puts "users created!"

puts "creating vegetables..."
vegetables_attributes = [
 { name: 'carotte' ,
  vegetabletype: 'racines',
  month_planted:['Mai','Juin','Juillet','Aout','Septembre','Octobre','Novembre'],
  distance_between: 5 ,
  luminosity: 3,
  humidity: 3,
  height: 30,
  harvest_time: 65,
  aromatics: ['ciboulette', 'coriandre'],
  friends: ['poireau', 'oignon', 'ail', 'romarin', 'échalotte', 'ciboulette', 'sauge'],
  ennemies: ['betterave'],
  frost_resistant: 3,
  photo: 'terracognita/carrot',
 },
  { name: 'endive' ,
  vegetabletype: 'feuilles',
  month_planted:['Mai','Juin'],
  distance_between: 25 ,
  luminosity: 1,
  humidity: 3,
  height: 20,
  harvest_time: 40,
  aromatics: '',
  friends: ['radis', 'chou', 'poireau', 'haricot', 'pois', 'courge', 'navet', 'carotte'],
  ennemies: '',
  frost_resistant: 2,
  photo: 'terracognita/',
 },
  { name: 'épinard' ,
  vegetabletype: 'feuilles',
  month_planted:['Mai','Juin','Juillet','Aout','Septembre','Octobre'],
  distance_between: 4 ,
  luminosity: 3,
  humidity: 3,
  height: 30,
  harvest_time: 45,
  aromatics: ["oeillet d'inde", "souci"],
  friends: ['laitue', 'concombre', 'pois', 'poireau', 'chou'],
  ennemies: ['pomme de terre', 'tomate', 'poivron'],
  frost_resistant: 2,
  photo: 'terracognita/',
 },
  { name: 'courgette' ,
  vegetabletype: 'fruits',
  month_planted:['Mars','Avril', 'Mai'],
  distance_between: 100 ,
  luminosity: 3,
  humidity: 3,
  height: 90,
  harvest_time: 100,
  aromatics: ['basilic'],
  friends: ['basilic', 'capucine', 'mais', 'pomme de terre'],
  ennemies: ['radis'],
  frost_resistant: 1,
  photo: 'terracognita/',
 },
 { name: 'laitue' ,
  vegetabletype: 'feuilles',
  month_planted:['Mars','Avril', 'Mai'],
  distance_between: 30 ,
  luminosity: 1,
  humidity: 3,
  height: 25,
  harvest_time: 50,
  aromatics: ['aneth'],
  friends: ['betterave', 'carotte', 'cerfeuil', 'chou', 'concombre', 'fève', 'fraise', 'navet', 'oignon', 'poireau', 'pois', 'radis'],
  ennemies: ['courge', 'persil', 'roquette'],
  frost_resistant: 3,
  photo: 'terracognita/lettuce',
  photo: 'terracognita/lettuce',
 },
 { name: 'tomate cerise' ,
  vegetabletype: 'fruits',
  month_planted:['Mai','Juin'],
  distance_between: 50 ,
  luminosity: 3,
  humidity: 3,
  height: 200,
  harvest_time: 80,
  aromatics: ['basilic','persil', 'œillet', "Rose d'Inde", 'menthe', 'sauge'],
  friends: ['asperge','poireau','carotte','pois','laitue','radis','ail', 'ciboulette','oignon'],
  ennemies: ['fenouil','maïs','pomme de terre','haricot', 'concombre', 'chou-rave','betterave'],
  frost_resistant: 1,
  photo: 'terracognita/',
 },
 { name: 'aubergine' ,
  vegetabletype: 'fruits',
  month_planted:['Février','Mars','Avril'],
  distance_between: 70 ,
  luminosity: 3,
  humidity: 3,
  height: 70,
  harvest_time: 120,
  aromatics: '',
  friends: ['haricot', 'poivron'],
  ennemies: ['pomme de terre'],
  frost_resistant: 1,
  photo: 'terracognita/',
 },
 { name: 'potimarron' ,
  vegetabletype: 'fruits',
  month_planted:['Mars','Avril'],
  distance_between: 120 ,
  luminosity: 3,
  humidity: 2,
  height: 30,
  harvest_time: 90,
  aromatics: ['basilic', 'capucine'],
  friends: ['mais', 'pomme de terre'],
  ennemies: ['radis'],
  frost_resistant: 1,
  photo: 'terracognita/pumpkin',
 },
 { name: 'radis' ,
  vegetabletype: 'racines',
  month_planted:['Mars','Avril', 'Mai','Juin','Juillet','Aout'],
  distance_between: 5 ,
  luminosity: 3,
  humidity: 2,
  height: 10,
  harvest_time: 30,
  aromatics: ['cerfeuil'],
  friends: ['carotte','épinard','haricot','laitue','pois','tomate','ail'],
  ennemies: ['chou','courge'],
  frost_resistant: 3,
  photo: 'terracognita/radish',
 },
 { name: 'poireau' ,
  vegetabletype: 'racines',
  month_planted:['Février','Mars','Avril', 'Mai','Juin'],
  distance_between: 15 ,
  luminosity: 3,
  humidity: 2,
  height: 70,
  harvest_time: 90,
  aromatics: "",
  friends: ['asperge','carottes','céleri','fenouil','fraise','laitue', 'oignon','tomate'],
  ennemies: ['betterave','chou','courge','persil','pois','poivron'],
  frost_resistant: 3,
  photo: 'terracognita/leek',
 },
 { name: 'haricot' ,
  vegetabletype: 'fruits',
  month_planted:['Mai','Juin'],
  distance_between: 25 ,
  luminosity: 3,
  humidity: 1,
  height: 40,
  harvest_time: 60,
  aromatics: ['souci'],
  friends: ['aubergine', 'carotte', 'céleri', 'chou', 'épinard', 'fraise', 'laitue', 'maïs', 'navet', 'pomme de terre', 'radis', 'souci'],
  ennemies: ['ail', 'betterave', 'échalote', 'fenouil', 'oignon'],
  frost_resistant: 1,
  photo: 'terracognita/',
 },
 { name: 'pomme de terre' ,
  vegetabletype: 'racines',
  month_planted:['Avril', 'Mai','Juin'],
  distance_between: 30 ,
  luminosity: 3,
  humidity: 2,
  height: 70,
  harvest_time: 90,
  aromatics: ['capucine', 'souci', 'lin'],
  friends: ['ail',  'céleri', 'chou', 'fève', 'haricot', 'pois', 'tomate'],
  ennemies: ['aubergine', 'concombre', 'maïs', 'oignon'],
  frost_resistant: 1,
  photo: 'terracognita/potato',
 },
 { name: 'tomate' ,
  vegetabletype: 'racines',
  month_planted:['Avril', 'Mai','Juin'],
  distance_between: 30 ,
  luminosity: 3,
  humidity: 2,
  height: 70,
  harvest_time: 90,
  aromatics: ['basilic','persil', 'souci', 'ciboulette'],
  friends: ['asperge','poireau','carotte','pois','laitue','radis','ail', 'oignon'],
  ennemies: ['fenouil','maïs','pomme de terre','haricot', 'concombre', 'chou-rave','betterave'],
  frost_resistant: 1,
  photo: 'terracognita/tomato',
 },
 { name: 'mâche' ,
  vegetabletype: 'feuilles',
  month_planted:['Mars','Avril'],
  distance_between: 5 ,
  luminosity: 3,
  humidity: 2,
  height: 15,
  harvest_time: 80,
  aromatics: ['souci', 'romarin', 'sarriette', 'sauge', 'thym'],
  friends: ['chou','fraise', 'poireau', 'oignon'],
  ennemies: "",
  frost_resistant: 3,
  photo: 'terracognita/mache',
 },
 { name: 'fraise' ,
  vegetabletype: 'feuilles',
  month_planted:['Mars','Avril'],
  distance_between: 30,
  luminosity: 2,
  humidity: 2,
  height: 30,
  harvest_time: 30,
  aromatics: ['ciboulette', 'souci', 'thym'],
  friends: ['ail', 'échalote', 'épinard', 'haricot', 'laitue', 'oignon', 'poireau', 'tomate'],
  ennemies: ['chou'],
  frost_resistant: 3,
  photo: 'terracognita/strawberry',
 },
 { name: 'petit pois' ,
  vegetabletype: 'fruits',
  month_planted:['Mars','Avril', 'Mai'],
  distance_between: 10,
  luminosity: 3,
  humidity: 2,
  height: 150,
  harvest_time: 60,
  aromatics: '' ,
  friends: ['carotte', 'céleri', 'chou', 'épinard', 'concombre', 'laitue', 'navet', 'pomme de terre' , 'radis'],
  ennemies: ['ail', 'échalote', 'haricot', 'oignon', 'poireau', 'tomate'],
  frost_resistant: 2,
  photo: 'terracognita/peas',
 },
 { name: 'asperge' ,
  vegetabletype: 'fruits',
  month_planted:['Février','Mars','Avril'],
  distance_between: 30,
  luminosity: 3,
  humidity: 1,
  height: 150,
  harvest_time: 1095,
  aromatics: ['sauge'],
  friends: ['tomate'],
  ennemies: '',
  frost_resistant: 2,
  photo: 'terracognita/asparagus',
 },
 { name: 'concombre' ,
  vegetabletype: 'fruits',
  month_planted:['Mars','Avril', 'Mai'],
  distance_between: 30,
  luminosity: 3,
  humidity: 3,
  height: 30,
  harvest_time: 65,
  aromatics: ['sauge', 'tournesol', 'basilic', 'capucines'],
  friends: ['céleri', 'chou', 'haricot', 'laitue', 'oignon', 'pois'],
  ennemies: ['pomme de terre', 'tomate'],
  frost_resistant: 1,
  photo: 'terracognita/',
 },
 { name: 'céleri' ,
  vegetabletype: 'feuilles',
  month_planted:['Février','Mars','Avril'],
  distance_between: 15,
  luminosity: 3,
  humidity: 3,
  height: 40,
  harvest_time: 170,
  aromatics: ['raifort'],
  friends: ["betterave", "carotte", "chou", "concombre", "haricot", "poireau", "pois", "radis", "tomate"],
  ennemies: ["laitue", "pomme de terre"] ,
  frost_resistant: 1,
  photo: 'terracognita/',
 },
 { name: 'poivron' ,
  vegetabletype: 'fruits',
  month_planted:['Mars','Avril', 'Mai'],
  distance_between: 45,
  luminosity: 3,
  humidity: 3,
  height: 70,
  harvest_time: 90,
  aromatics: ["oeillet d'inde", "souci", 'persil', 'bourrache'],
  friends: ['aubergine', 'carotte', "oignon", "pois", "tomate", "trèfle"],
  ennemies: '',
  frost_resistant: 1,
  photo: 'terracognita/',
 },
 { name: 'oignon' ,
  vegetabletype: 'racines',
  month_planted:['Février','Mars'],
  distance_between: 10,
  luminosity: 3,
  humidity: 1,
  height: 60,
  harvest_time: 95,
  aromatics: ['persil'] ,
  friends: ['betterave', 'carotte', 'concombre', 'courge', 'courgette', 'échalote', 'fraise', 'laitue', 'poireau', 'tomate'] ,
  ennemies: ['chou', 'fève', 'haricot', 'navet', 'pois', 'pomme de terre'],
  frost_resistant: 3,
  photo: 'terracognita/',
 },
]

Vegetable.create!(vegetables_attributes)
puts "vegetables created!"

puts "creating potager..."
potager_attributes = [{ user: toto ,
  length: 4,
  width: 4,
  freezing: false ,
  orientation: "S",
  start_month: "Mai",
 },
 { user: bob ,
  length: 2,
  width: 5,
  freezing: true ,
  orientation: "E",
  start_month: "Avril",
 }

]
Potager.create!(potager_attributes)
puts "potager created!"
